[package]
name = "otpg-test"
version = "0.1.0"
edition = "2024"

[dependencies]
chacha20poly1305.workspace = true
otpg-core = {path = "../otpg-core"}
otpg-contrib = {path = "../otpg-contrib"}
totp-rs.workspace = true
chrono.workspace = true
blake3.workspace = true
bincode.workspace = true